version: '3.7'

services:
  webserver:
    image: nginx:alpine
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/laravel
    depends_on:
      - backend
    networks:
      - main

  database:
    image: mysql:5.7
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_PORT: '${MYSQL_PORT}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - main

  backend:
    image: lib/fpm:latest
    container_name: lib_php
    build:
      context: ./
      target: prod
    volumes:
      - ./:/var/www/html/laravel
    expose:
      - 9000
    depends_on:
      - database
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  db_data:
